### ISSUE TITLE
Results should be an array

### ISSUE THREAD

**Issue by jasonbukowski** [lontivero/PyChainpoint#1]
Great work on this, I just wanted to call you attention to a couple things that I feel are worth considering.

The original design was to have the anchor results as an array because the receipt supports, and may optionally include, multiple anchor points, such as one to Bitcoin and a second to Ethereum. While that has not been implemented in the validation functions yet, I suggest the result should include anchor points in an array for future compatibility.

For example -> 
anchors: [
  {
    type: 'BTCOpReturn',
    source_id: 'f3be82fe1b5d8f18e009cb9a491781289d2e01678311fe2b2e4e84381aafadee',
    exists: true
  }
]

On a related note, the 'exists' boolean is meant to be displayed if and only if the presence of the merkle root value was actually confirmed to exist on the blockchain within the specified transaction id (sourceId). 'is_valid' should tell you if the receipt format, values, and proof path are proper globally for the receipt, while 'exists' (optionally) validates the existence of a value in a particular transaction for each anchor item.
I use my own node package https://www.npmjs.com/package/blockchain-anchor to call 3rd party APIs to confirm transaction values. This package was in fact inspired by a similar one written in Python which you will certainly find useful for this task https://github.com/F483/btctxstore

**Comment by lontivero** [comment]
@jasonbukowski I really appreciate you take the time for reviewing my implementation and provide feedback. 

I´ve created this package because i need it urgently for a real project in which i am working on. That means i code it for my project first and then i decided to open source it with the same license the nodejs module has (MIT). That means that, if well it is useful for me as it is, it still needs a bit of extra work.

Multiple anchors is one of those features that my project doesn't need but i have to add to pychainpoint package. I have to do it because I want to share an useful package and not one that is only useful for me. 

About the _exists_ attribute, i am going to remove it. IMO the isValidReceipt method has one or two responsibilities depending on an boolean (flag) parameter. I don't like that. I would like to separate those responsibilities. 

Thank you for your work, I really think we needed a standard protocol and data format for verifying proof-of-existance or timestamping.

**Comment by jasonbukowski** [comment]
@lontivero I understand completely... and I often do the same for my own time critical projects. 

I'm happy that you are finding Chainpoint to be a useful standard for your project and wish you great success. We are currently working with the W3C to formalize Chainpoint as the standard for proof of existence receipts. If you are interested in being part of helping to shape the future of Chainpoint, I invite you to join our group here http://w3.org/community/chainpoint.

**Comment by lontivero** [comment]
@jasonbukowski thank you for inviting me to join your group. Sadly, I wasn't able to get my employer approval. Anyway, I will share my comments when I have something.
